---
name: "Install_tools"
description: "Install required packages for the job"


runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
          node-version: 20
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: 1.9.5
    - name: Install Go
      uses: actions/setup-go@v5
      with:
          go-version: 1.23.0
          cache: false
    - name: Check Docker version
      shell: bash
      run: docker --version
      
    # - name: Install sudo
    #   shell: bash
    #   run: apt-get update && apt-get install -y sudo
        
    - name: Install Azure CLI
      shell: bash
      run: curl -sL https://aka.ms/InstallAzureCLIDeb |  bash

    - name: Check Azure CLI version
      shell: bash
      run: |
          az --version

