---
name: "acr_work"
description: "ACR work"

runs:
  using: composite
  steps:
    - name: Log in to Azure Container Registry
      shell: bash
      run:  |
          systemctl status docker
          systemctl start docker
          systemctl enable docker
          systemctl daemon-reload

        #  az acr login --name iaggbsacrcorecrtestuksouth01
