---
name: "acr_work"
description: "ACR work"

runs:
  using: composite
  steps:

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
      
    - name: Log in to Azure Container Registry
      shell: bash
      run: |
        TOKEN=$(az acr login --name iaggbsacrcorecrtestuksouth01 --expose-token --output tsv --query accessToken)
        
        docker login iaggbsacrcorecrtestuksouth01.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin <<< $TOKEN

        docker build -t iaggbsacrcorecrtestuksouth01.azurecr.io/image_pushed_from_cicd_runner:v1 .

        docker push iaggbsacrcorecrtestuksouth01.azurecr.io/iaggbsacrcorecrtestuksouth01:v1


