---
name: "acr_work"
description: "ACR work"

runs:
  using: composite
  steps:
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      shell: bash
      run: |
       
        docker run -v /var/run/docker.sock:/var/run/docker.sock -i docker sh


