---
name: "acr_work"
description: "ACR work"

runs:
  using: composite
  steps:
    - name: Log in to Azure Container Registry
      shell: bash
      run:  |
         az acr login --name iaggbsacrcorecrtestuksouth01
