# This is a basic workflow to help you get started with Actions

name: Pull Request

on:
  pull_request:
    branches:
      - main
    types: ["opened", "reopened", "synchronize"]
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    environment: env-acrpull-test
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install Tooling
        uses: ./.github/actions/install_tools
      - name: Acr Work
        uses: ./.github/actions/acr_work
  push:
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    environment: env-acrpush-test
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install Tooling
        uses: ./.github/actions/install_tools
      - name: Acr Work
        uses: ./.github/actions/acr_work
          
            