# This is a basic workflow to help you get started with Actions

name: Pull Request

on:
  pull_request:
    branches:
      - main
    types: ["opened", "reopened", "synchronize"]
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    environment: env-acrpull-test
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install Tooling
        uses: ./.github/actions/install_tools
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Configure Azure OIDC
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Get ACR token
        id: get-acr-token
        run: |
          TOKEN=$(az acr login --name iaggbsacrcorecrtestuksouth01 --expose-token --output tsv --query accessToken)
          echo "::set-output name=token::$TOKEN"

      - name: Log in to ACR
        run: |
          echo "${{ steps.get-acr-token.outputs.token }}" | docker login iaggbsacrcorecrtestuksouth01.azurecr.io --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t iaggbsacrcorecrtestuksouth01.azurecr.io/image_pushed_from_cicd_runner:v1 .

      - name: Push Docker image
        run: |
          docker push iaggbsacrcorecrtestuksouth01.azurecr.io/image_pushed_from_cicd_runner:v1